### ISSUE TITLE
iPhone 5(s) lens?

### ISSUE THREAD

**Issue by walterav1984** [tobetz/LegoMicroscope#10]
Both iPhone 5 and iPhone 5s are mentioned in the article but do they share the same back/rear camera module, the picture shows a 821-1592-a module? How about iPhone 5c?

**Comment by tobetz** [comment]
The details about the camera are actually not too important. You only need to get access to the lens, hence I would use a module that is simple to get and affordable. You might need to fiddle around a bit with the mounting, but I am fully convinced it is possible, also with a iPhone 5c module.

**Comment by walterav1984** [comment]
I'm sorry if my question put the focus on the module, but it was more intended to be about which specific iPhone 5 model's lens was actually used or even usable?

In other words should a functioning "iPhone 5" be torn apart including disassembling/breaking the camera module possible noticing that the lens is not usable because it was the "iPhone 5s" lens used for this project?

**Comment by tobetz** [comment]
I wold never make a functioning iPhone unusable for these purposes. You should be able to get the camera module replacements quite cheap over eBay. I can only guarantee you for the module I had used, but physics does not care which smartphone you have. All you need is a lens with a short focal distance, and good optical properties (spherical and chromatic aberration correction). Since smartphones are very slim, the first point is always true for each smartphone camera. The optical properties largely decide over the image quality. Hence, any smartphone that was produced after about 2010 has here already lenses with good optical properties. If you absolutely not want to get a camera module, maybe you have an old broken smartphone that already includes a reasonable camera. In that case I would opt opening this one. 
Hope that helps,
best,
Timo

**Comment by walterav1984** [comment]
> Hence, any smartphone that was produced after about 2010 has here already lenses with good optical properties.

Good to know that its apparantly not being dependent on a specific iPhone model its lens but that more different phone brands/lenses may do the job.

> If you absolutely not want to get a camera module, 

It was more a about confusing semi-specific info about mentioning both iPhone 5 and iPhone 5s in "Readme.MD" and possible hit or miss of buying/recycling one of these models.

Thanks for explaining the actual needs and properties.
