### ISSUE TITLE
Questions and Comments

### ISSUE THREAD

**Issue by Muchajoe** [tobetz/LegoMicroscope#11]
Hi
i really like this Project. I have a few questions and comments.

1. What is the benefit of this LegoConstruction? I think it is the high resolution? Is this overall "better" than a 20$ (USB) Microscope or something like that? Or is it only for the kids to learn and try things and modify? So does it make sense for me to build this or should i buy one of the cheap Microscopes if i only want to use it as Microscope? Or would i get a better one with this LegoMicroscope?

2. The Bricklink list contain parts that are not longer produced and available. The Most of these parts are replaced by a renamed similar one. I can replace the most of them with them, that should work. But The Lightbrick is not available at all. So i have to find a easy and cheap way to light it up.

3. In the scientific paper there is a scheme. This is (for me) not 100% clear. You named the lenses: First and Second lense? I Think it would be much easier if you named the lenses (in the scheme .jpg too) Ocular and Objective. I guess the "second lense" is the Ocular?

4. Why i change the distance between the lenses? in conventional Microscopes i change the distance between the Object and the Objective.

**Comment by tobetz** [comment]
Dear Muchajoe,

I am happy that you like it! Here my answers to your questions: 

1) The benefit is to excite kids. As you say, there are other cheap solutions that you connect to your computer and you will get good resolution. These are great if you want to a cheap way to look at samples. By the way, if you want it good and cheap, you should take a look at the [Foldscope](https://www.foldscope.com/), which is really amazing. 
However, if you want kids to learn how a microscope works there is nothing better than constructing one. I can't let my son disassemble the research microscope in the lab, but he can play and test ideas with the Lego microscope. So that is the benefit I think. 
If you want to build a microscope: Go for the Lego Microscope
If you want a cheap microscope, look into the other solutions... The Lego parts are actually not cheap!

2) Hmm, you can get any other color of the Lego Bricklink and then replace the LED. There are several instructions out there, and we have also a video in the instructions. It is really simple and you don't need soldering or difficult things.... just a screwdriver. 
If even other colors are not available, in the beginning I just put my cellphone below the sample. For this you need to modify the base, but it really is easy if you like playing with Lego.
Regarding the parts... the problem is often just the color. Of course the color does not matter!

3) I understand the confusion. Sorry about this. The reason is that we also generated an educational 'walk-through' for kids, where we did not want to confuse them with words like 'ocular' and 'objective', and where we first introduce the lenses as magnifying glasses. In the scheme, you are right, the second lens is the ocular, and the first lens is the objective. 

4) I was not able to construct a stable situation where I would do what you suggest. From an optics point of view you can change either the distance between the lenses or between the lenses and the objective. However, what 'normal' microscopes do is much cleaner (i.e. fixing the distance between he tow lenses) just as you suggest. The price we pay for our solution is that the magnification depends a bit on the details of the observers eye, for example if the observer usually wears glasses, things are getting different. 
But what can I say: This design worked, and I failed in attempting the other design. If you manage to construct it in a stable way, let me know then we include it in the GitHub page :-)

If you have more questions, don't hesitate to write again!

best,
Timo
