### ISSUE TITLE
Need some help...

### ISSUE THREAD

**Issue by sjmerel** [tobetz/LegoMicroscope#12]
First off -- I love this idea.  However, I haven't managed to be able to see a clear image through the eyepiece yet, and was hoping for some help.

I have an iPhone 5 camera assembly from eBay that I'm using for the objective:
![image](https://i.postimg.cc/sxQMpcZP/2021-07-21-17-18-40.jpg) ![image](https://i.postimg.cc/WpCFsQQ5/2021-07-21-17-18-47.jpg)
Question: is there a correct orientation for the objective?  I think I have matched what was in the assembly PDF, but I'm not sure.  (Some text explaining how to extract the lens from the camera assembly, and how to attach it to the Lego, would have been helpful here.  I used hot glue.)

Following the discussion in issue #9, I'm using this lens for the eyepiece (a.k.a. "the large magnifying glass")
https://www.surplusshed.com/pages/item/L1828.html

And I'm using this one for what you call "the small magnifying glass":
https://www.edmundoptics.com/p/18-x-20mm-fl-grade-1-double-convex-lens/24352/
![image](https://i.postimg.cc/Pr1bLWns/2021-07-21-17-27-41.jpg)
I sanded down the edges of the lens slightly to fit in the center of the Lego ring.  Since this lens seems to be much thinner than what you're using, the other Lego ring that would go on top doesn't make contact with the lens, so I've left it off for now; the lens is just sitting there under its own weight.  

Here's where I get confused.  The full PDF instructions tell you to put the objective on the focusing assembly, but then the small magnifying glass is just sitting there next to it, like what I have here:
![image](https://i.postimg.cc/FHRRtvZW/2021-07-21-17-37-40.jpg)

But presumably the fully assembled microscope has that small lens attached to the focusing assembly too?  Something like this?
![image](https://i.postimg.cc/9Q6jxHNq/2021-07-21-17-44-00.jpg)

As I said, I can't seem to get a clear image with the setup I've just described... am I missing something?

**Comment by Muchajoe** [comment]
The Large Magnification glass is the iphone lense.
The Low Magnification glass is the 18 mm focal length 26.5 mm

I think in total you look throu 2 lenses. but you can change the lense on the focusing assembly. So the eyepiece (ocular) lense stay there. But you can change the Objective lense. If you want more zoom you have to use the Iphone lense. with less zoom you have to assemble the low magnification lense

**Comment by tobetz** [comment]
Dear sjmerel,

Muchajoe is right. The idea is to look through 2 lenses, as these make up the Microscope. 
However, the two lenses are ocular (the part on top of the microscope) and the objective. 
What you show in the final image would be a 3 lens system, which would be a nightmare to align (although in theory you can get magnification there too.

But step by step. Let me answer your questions in the order you pose them:
1)   Question: is there a correct orientation for the objective?
-> Yes there is. The flat side should face down. In the Instruction on page 36, we tried to give some help for the mounting and disassembly of the camera module. The simplest thing is to use some adhesive tape (Scotch) and a microscope coverslip to simply fix it by slight clamping. But your approach seems to be even more stable! 

Comments: And I'm using this one for what you call "the small magnifying glass":
-> Yep, the naming might be somewhat confusing. The reason is that we have generated a little walk-through for the kids, and we first introduce the lenses as magnifying glasses, then guide the kids to the situation of a microscope... to be consistent with our own description, we kept the term. But I understand that this is strange if you only use the straight plan. Sorry for the confusion. 
Regarding the mounting: I just received this lens too. I suggest the following to get it fixed. 
![image](https://user-images.githubusercontent.com/5574938/126801538-852fab43-a24b-417f-95f0-25cd2a74c78a.png)

And then mounted: 
![image](https://user-images.githubusercontent.com/5574938/126801676-d14ecd98-af68-45e0-90b3-69a6319f0e7c.png)

This should keep it fixed. 

Question: 
Here's where I get confused. The full PDF instructions tell you to put the objective on the focusing assembly, but then the small magnifying glass is just sitting there next to it, like what I have here:

-> The idea is to have two magnifications just as Muchajoe wrote. You can either use the iPhone 'Objective' or the 'Small Magnifying Glass' based objective. 

I attached an image of two mounting next to each other: 
![image](https://user-images.githubusercontent.com/5574938/126802166-9dcfc42c-acc9-4566-9320-654665582637.png)


I hope this helps!

By the way. I also got an Edmund lens for the objective that works well. I will add this in the issue where the two lenses are suggested. 

best,
Timo
