### ISSUE TITLE
US lens options

### ISSUE THREAD

**Issue by pfolk** [tobetz/LegoMicroscope#9]
Awesome project.

Shipping from AstroMedia in UK is reported by them as 6-10 weeks, so I went searching for some US sources for the lenses.  I didn't find exact matches but my understanding is that exact matches are probably not critical---but I am no optics expert so I wanted to run them by you, and recommend you include them as options if they seem like they will work.

What I ended up finding that seemed most similar to the two lens types you used are:

- 37mm Dia. x -106mm FL, Grade 2, Plano-Concave Lens - Stock number 96-190 - https://www.edmundoptics.com/p/37mm-dia-x106mm-fl-grade-2-plano-concave-lens-/32822/
- 15mm Dia x 27mm FL, Grade 1, Plano-Convex Lens - Stock number 43-809 - https://www.edmundoptics.com/p/15mm-dia-x-27mm-fl-grade-1-plano-convex-lens/5297/

1) Can you confirm these will work with minimal modification of the instruction plan?
2) You might want to update your README to reference these items, if so.

**Comment by tobetz** [comment]
Hi Peter,
Thanks a lot for looking for a US based supply. I had Edmund as expensive source in the back of my head, but you are right, it's really affordable. I hope you have not yet ordered the lenses. The first option you suggest will not work, as it has a negative focal length (its an concave lens, that would not work at all). 

I suggest to get a single bi-convex lens with higher power than two low powers plan-convex lenses in the description. This one should work well:  
- 34 x 40mm FL, Grade 2, Double-Convex Lens Stock #94-826 [ https://www.edmundoptics.com/p/34-x-40mm-fl-grade-2-double-convex-lens/32587/](https://www.edmundoptics.com/p/34-x-40mm-fl-grade-2-double-convex-lens/32587/)
This would already have a similar power to the two pan-convex plastic lenses we mention. 

Regarding the second lens, your suggestion should work in principle, but I am just a bit worried that it will drop through the hole in the lego ring part we used for mounting. I can suggest that I order it here and test it first, but then you would need to wait for a week or two. In principle, you can use any lens, and you just need to come up with a lego-solution to mount it. It needs to be a convex lens (hence with positive focal length), and the shorter the focal length, the higher will be magnification. The price you pay for higher magnification is a smaller field of view. So if you want you can even buy several lenses, and then have a full selection of magnifications.  

Better choices here might be the following two options: 
- 18 x 15mm FL, Grade 1, Double-Convex Lens Stock #74-282  [https://www.edmundoptics.com/p/18-x-15mm-fl-grade-1-double-convex-lens/24796/](https://www.edmundoptics.com/p/18-x-15mm-fl-grade-1-double-convex-lens/24796/)
-  18 x 20mm FL, Grade 1, Double-Convex Lens Stock #73-312 [https://www.edmundoptics.com/p/18-x-20mm-fl-grade-1-double-convex-lens/24352/](https://www.edmundoptics.com/p/18-x-20mm-fl-grade-1-double-convex-lens/24352/)

The second is closer to what we used, the first one gives a higher magnification. Both should fit quite perfectly. 

Let me know which of the solutions worked, and they I will include Edmund as a parts source in the description. 

Best,
Timo

**Comment by sjmerel** [comment]
FYI, that first one (34 x 40mm FL) has been discontinued. 

If I'm looking for a replacement, I presume I want a double-convex lens with a focal length of 40mm, right?  How close to 34mm does the diameter need to be?

thanks!

**Comment by pfolk** [comment]
I've already learned something--I now know how to add focal lengths!  1/f1 + 1/f2 = 1/f3, or in this case two 34x106 lenses = one 34x53 lens.

I found a site with great prices on double-convex 34mm x 52mm focal length lenses, nearly identical to what you use: https://www.surplusshed.com/pages/item/L1828.html ; Not sure how many they have but enough to sell 10-packs =)

18mm x 25ishmm focal length lenses are harder to come by; the best options on that site are:
https://www.surplusshed.com/pages/item/L3857.html - 17mm dia 23mm f
https://www.surplusshed.com/pages/item/L13764.html - 19.5mm dia 22mm f

**Comment by tobetz** [comment]
> FYI, that first one (34 x 40mm FL) has been discontinued.
> 
> If I'm looking for a replacement, I presume I want a double-convex lens with a focal length of 40mm, right? How close to 34mm does the diameter need to be?
> 
> thanks!

In fact, the Lego housing is quite flexible to be extended. Initially we had different lenses, but they were too expensive. So the 34mm diameter, and roughly 50mm focal length lenses will work for sure. If you are happy to fiddle around with the Lego (lot's of fun, actually), I am sure you can manage to get also other lenses to work. 
If you increase the focal length too much, you will start getting trouble to focus in the end, or you may increase then the distance between the 'objective' and the occular (i.e. by adding a few more levels of lego on the tower). It is actually the cool thing about Lego that you should be able to make it work with many different lenses. 

If the diameter is too large, it will not fit anymore in the housing. In the current design, +- 1mm is ok. If more, you will have to get creative.

let me know if you have more questions. 
best,
Timo

**Comment by tobetz** [comment]
> I've already learned something--I now know how to add focal lengths! 1/f1 + 1/f2 = 1/f3, or in this case two 34x106 lenses = one 34x53 lens.
> 
> I found a site with great prices on double-convex 34mm x 52mm focal length lenses, nearly identical to what you use: https://www.surplusshed.com/pages/item/L1828.html ; Not sure how many they have but enough to sell 10-packs =)
> 
> 18mm x 25ishmm focal length lenses are harder to come by; the best options on that site are:
> https://www.surplusshed.com/pages/item/L3857.html - 17mm dia 23mm f
> https://www.surplusshed.com/pages/item/L13764.html - 19.5mm dia 22mm f

Dear Peter,

yep, you got it :-) this is the lens equation and there is much more to learn:-)

The webpage you found is great!
I suggest you try the lens:
L12228 PCX 18MM X 22MM

It's a planconvex lens but that is even better (the difference is in the spherical aberration that you risk to get, but the problem is not severe). You can even try if you see a difference when mounting it with the flat side down or up :-). This is then the next level to learn.... what gives better quality??

In the mounting for the 18mm lens based objective, I would not go to the 17mm diameter lens, because I think it will then fall through opening of the mounting part. But you can go up to 20mm. That will still fit in. 

Let me know if you have further questions,
best,
Timo

**Comment by tobetz** [comment]
Ok, so I just got the Edmund lenses. 

Regarding the Ocular, I think the lens: 
34 x 40mm FL, Grade 2, Double-Convex Lens Stock #94-826
https://www.edmundoptics.com/p/34-x-40mm-fl-grade-2-double-convex-lens/32587/

Works well as ocular. You will have to change the distance between the eye and the lens. Briefly, since the focal length is shorter, you need to bring the eye closer to the lens. Below what I did to make it work. However, I had no time to fully check it.

![image](https://user-images.githubusercontent.com/5574938/126805982-cdcb90ed-e105-40e0-b726-dadabe736d57.png)



Regarding the other lens which we use as low magnifying objective. Here the solution: 
18 x 20mm FL, Grade 1, Double-Convex Lens Stock #73-312 https://www.edmundoptics.com/p/18-x-20mm-fl-grade-1-double-convex-lens/24352/
works well with the design. I could fix it by simply clamping the lens down in the holder. Try this approach: 

![image](https://user-images.githubusercontent.com/5574938/126806253-56c1b031-30ca-4d54-9607-8cf7f3ea9ef5.png)


and for clamping put the top in the lens:

![image](https://user-images.githubusercontent.com/5574938/126806315-f5712fbf-0b4e-45e4-9383-a453cde4937d.png)


These are good lenses, actually even better than what we have in the original design!

best,
Timo
